# Generated by Django 3.0.4 on 2020-04-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='purchase_date',
            field=models.DateTimeField(verbose_name='date purchased'),
        ),
    ]
